project:
  type: website
  output-dir: _site
  preview:
    port: 7778  

website:
  title: "fasttrackpy"
  favicon: assets/logo_f2.png
  page-navigation: true
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: reference/
        text: Package reference 
    right:
      - icon: github
        href: https://github.com/JoFrhwld/fasttrackpy
  sidebar:
      - id: get-started
        logo: assets/logo_f2.png
        title: Get Started
        style: floating
        align: left
        contents:
          - index.qmd
          - usage/getting_started.qmd
          - usage/all_arguments.qmd
          - usage/pythonic_use.ipynb
          - usage/dct.ipynb

metadata-files:
  - reference/_sidebar.yml

resources: 
  - objects.inv
filters:
  - "interlinks"  
interlinks:
  fast: true
  sources:
    numpy:
      url: https://numpy.org/doc/stable/
    python:
      url: https://docs.python.org/3/
    aligned_textgrid:
      url: https://forced-alignment-and-vowel-extraction.github.io/alignedTextGrid/
    parselmouth:
      url: https://parselmouth.readthedocs.io/en/stable/

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 4

quartodoc:
  style: pkgdown
  dir: reference
  package: fasttrackpy
  sidebar: "reference/_sidebar.yml"
  parser: google
  render_interlinks: true
  sections:
    - title: Processing Functions
      desc: functions
      contents:
        - process_audio_file
        - process_directory
        - process_audio_textgrid
        - process_corpus
    - title: Classes
      desc: Classes
      contents:
        - name: OneTrack
          children: embedded
        - name: CandidateTracks
          children: embedded
    - title: Outputs
      desc: Data outputs
      contents:
        - processors.outputs.pickle_candidates
        - processors.outputs.unpickle_candidates

    - title: Smoothers
      desc: Smoother
      contents:
        - Smoother
        - processors.smoothers.Smoothed
        - processors.smoothers.dct_smooth
        - processors.smoothers.dct_smooth_regression
    - title: Losses
      desc: Losses
      contents:
        - Loss
        - processors.losses.lmse
        - processors.losses.mse
    - title: Aggs
      desc: Aggs
      contents:
        - Agg
        - processors.aggs.agg_sum
    - title: Heuristic Classes
      desc: Heuristics Classes
      contents:
        - MinMaxHeuristic
        - SpacingHeuristic
    - title: Pre-specified Heuristics
      desc: Pre-specified Heuristics
      contents: 
        - kind: page
          #desc: "Heuristics"
          path: heuristics
          flatten: true
          contents: 
            - name: "processors.heuristic"
              members:
                - F1_Max
                - F4_Min
                - B2_Max
                - B3_Max
                - Rhotic
                - F3_F4_Sep
    - title: Utilities
      contents:
        - utils.safely
        - patterns.just_audio.is_audio
