# process_audio_textgrid { #fasttrackpy.process_audio_textgrid }

`process_audio_textgrid(audio_path, textgrid_path, textgrid_format=['Word', 'Phone'], target_tier='Phone', target_labels='[AEIOU]', min_duration=0.05, min_max_formant=4000, max_max_formant=7000, nstep=20, n_formants=4, window_length=0.025, time_step=0.002, pre_emphasis_from=50, smoother=Smoother(), loss_fun=Loss(), agg_fun=Agg())`

_summary_

## Parameters

| Name                | Type        | Description                                   | Default             |
|---------------------|-------------|-----------------------------------------------|---------------------|
| `audio_path`        | str \| Path | _description_                                 | _required_          |
| `textgrid_path`     | str \| Path | _description_                                 | _required_          |
| `textgrid_format`   | list        | _description_. Defaults to ["Word", "Phone"]. | `['Word', 'Phone']` |
| `target_tier`       | str         | _description_. Defaults to "Phone".           | `'Phone'`           |
| `target_labels`     | str         | _description_. Defaults to "[AEIOU]".         | `'[AEIOU]'`         |
| `min_duration`      | float       | _description_. Defaults to 0.05.              | `0.05`              |
| `min_max_formant`   | float       | _description_. Defaults to 4000.              | `4000`              |
| `max_max_formant`   | float       | _description_. Defaults to 7000.              | `7000`              |
| `nstep`             | int         | _description_. Defaults to 20.                | `20`                |
| `n_formants`        | int         | _description_. Defaults to 4.                 | `4`                 |
| `window_length`     | float       | _description_. Defaults to 0.025.             | `0.025`             |
| `time_step`         | float       | _description_. Defaults to 0.002.             | `0.002`             |
| `pre_emphasis_from` | float       | _description_. Defaults to 50.                | `50`                |
| `smoother`          | Smoother    | _description_. Defaults to Smoother().        | `Smoother()`        |
| `loss_fun`          | Loss        | _description_. Defaults to Loss().            | `Loss()`            |
| `agg_fun`           | Agg         | _description_. Defaults to Agg().             | `Agg()`             |

## Raises

| Type      | Description   |
|-----------|---------------|
| TypeError | _description_ |

## Returns

| Type                    | Description                          |
|-------------------------|--------------------------------------|
| list\[CandidateTracks\] | list[CandidateTracks]: _description_ |