# process_audio_file { #fasttrackpy.process_audio_file }

`process_audio_file(path, xmin=0, xmax=None, min_max_formant=4000, max_max_formant=7000, nstep=20, n_formants=4, window_length=0.025, time_step=0.002, pre_emphasis_from=50, smoother=Smoother(), loss_fun=Loss(), agg_fun=Agg())`

Given the path to a single audio file, return a candidates track object.

## Parameters

| Name                | Type        | Description                                                                             | Default      |
|---------------------|-------------|-----------------------------------------------------------------------------------------|--------------|
| `path`              | str \| Path | Path to the audio file                                                                  | _required_   |
| `xmin`              | float       | Start time to process the audio. Defaults to 0.                                         | `0`          |
| `xmax`              | float       | End tome for processing audio. If None, defaults to the maximum time. Defaults to None. | `None`       |
| `min_max_formant`   | float       | The lowest max-formant value to try.  Defaults to 4000.                                 | `4000`       |
| `max_max_formant`   | float       | The highest max formant to try.  Defaults to 7000.                                      | `7000`       |
| `nstep`             | int         | The number of steps from the min to the max max formant.  Defaults to 20.               | `20`         |
| `n_formants`        | int         | The number of formants to track. Defaults to 4.                                         | `4`          |
| `window_length`     | float       | Window length of the formant analysis.  Defaults to 0.025.                              | `0.025`      |
| `time_step`         | float       | Time step of the formant analyusis window.  Defaults to 0.002.                          | `0.002`      |
| `pre_emphasis_from` | float       | Pre-emphasis threshold.  Defaults to 50.                                                | `50`         |
| `smoother`          | Smoother    | The smoother method to use.  Defaults to `Smoother()`.                                  | `Smoother()` |
| `loss_fun`          | Loss        | The loss function to use.  Defaults to Loss().                                          | `Loss()`     |
| `agg_fun`           | Agg         | The loss aggregation function to use.  Defaults to Agg().                               | `Agg()`      |

## Returns

| Type            | Description                        |
|-----------------|------------------------------------|
| CandidateTracks | A `CandidateTracks` object to use. |