name: Build Docs

on:
  push:
    branches: ["main", "dev"]

permissions:
  contents: read
  pages: write  

jobs:
  build-docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/docs.txt
          python -m pip install .
          quartodoc build --config docs/_quarto.yml
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and publish to gh pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
