name: Build Docs

on:
  push:
    branches: ["main", "dev"]

jobs:
  build-docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install Project
        run: 
          uv sync --group docs
      - name: Quardo Doc Build
        run: |
            cd docs
            uv run quartodoc build
            uv run python objects.py            
            uv run quartodoc interlinks
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and publish to gh pages
        run: |
          git config --global user.email "quarto-github-actions-publish@example.com"
          git config --global user.name "Quarto GHA Workflow Runner"
          uv run quarto publish gh-pages docs --no-browser