name: Build Docs

on:
  push:
    branches: ["main", "dev"]

jobs:
  build-docs:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements/docs.txt
          python -m pip install .
      - name: Quartodoc Build
        run: quartodoc build --config doc/_quarto.yml
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render and publish to gh pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: docs
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}